### ISSUE TITLE
smpl tensorflow

### ISSUE THREAD

**Issue by gnool** [CalciferZh/SMPL#10]
@CalciferZh  im trying to use the tensorflow version as I think it may be faster. However, how do I load the whole model and all its parameters into tensorflow only once, and then keep changing the model by only changing the beta? Is this possible? Otherwise it seems now that it runs slower than CPU version.

**Comment by CalciferZh** [comment]
Are you using beta as placeholder?

**Comment by gnool** [comment]
@CalciferZh Ah no, I didn't use placeholder (I'm actually not familiar with tensorflow). I simply ran smpl_tf.py, where I saw that betas were set as tf.constant. Could you advise what's the correct way of loading the SMPL model parameters, and then we just need to change beta/pose to update the model?

**Comment by CalciferZh** [comment]
`betas` `pose` and `trans` need to be `tf.placeholder` to build the graph. You need to refer to TensorFlow doc first.
