### ISSUE TITLE
preprocess: KeyError: 'cocoplus_regressor' 

### ISSUE THREAD

**Issue by bearpaw** [CalciferZh/SMPL#13]
Hi, when I run 
```
python preprocess.py ../smpl_python_v.1.0.0/models/basicModel_f_lbs_10_207_0_v1.0.0.pkl
```
I got the this error. I checked the keys of `src_data` and found that there is no `cocoplus_regressor`.

Did I load the wrong pkl file? Thank you in advance.

**Comment by CalciferZh** [comment]
Hi, I think your model is correct. This error is due to @Lotayou 's commit about another model (SMIL). Simply deleting line 22 in `preprocess.py` should fix this.

**Comment by bearpaw** [comment]
Got it! Thanks!
