### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by hideonInternet** [CalciferZh/SMPL#14]
Hi, I have a question about this:
`lrotmin = tf.squeeze(tf.reshape((R_cube - I_cube), (-1, 1)))`
I think that the code may correspond to the eq.9 in the paper. but the eq.9 is to subtract R_n(theta*) instead of an identity matrix. Are they have the same value? thanks a lot. btw, I have read the code offered by the paper writer, but I am still confused with that.
Thanks a lot:)

**Comment by CalciferZh** [comment]
Hi, I think they are the same. R_n(theta*) is the rotation matrix of zero pose, which should be an identity matrix.

**Comment by hideonInternet** [comment]
Thank you, I got it.
