### ISSUE TITLE
About rodtigues

### ISSUE THREAD

**Issue by LogWell** [CalciferZh/SMPL#15]
Hey, why does the first term have a cosine function?
https://github.com/CalciferZh/SMPL/blob/b8ace714166e12cc1005274fb64cd295f5b39e25/smpl_np.py#L154

**Comment by CalciferZh** [comment]
https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga61585db663d9da06b68e70cfbf6a1eac
