### ISSUE TITLE
pose parameter

### ISSUE THREAD

**Issue by dclcs** [CalciferZh/SMPL#16]
your job is great! 
I read the paper.In paper author just say "72 pose parameters ; 3 for each part plus 3 for the root orientation".I can understand it can calculated by axis-angle, but what's the meaning of root orientation?

**Comment by sebftw** [comment]
It is the zeroth joint I believe. So while the other pose parameters give angles between joints connected in the kinematic tree, the root orientation is just the initial orientation.
Changing the root orientation will then rotate the whole model.

**Comment by CalciferZh** [comment]
It's like a global rotation - rotating all parts of the model to some direction.

**Comment by dclcs** [comment]
I use the pose parameter to input the lbs algorithm implementation (the smpl source code).I can get the 3D position. I also use the pose[0] , joint[0] and joint[1], which can get the deformed point[1]. Like this , 
`deformed_point[1] = rodrigues(pose[0]).dot(joint[1] - joint[0]) + joint[1]`.I am confused......Is the axis-angle expression problem?
