### ISSUE TITLE
The specific meaning of shape parameters

### ISSUE THREAD

**Issue by YoungRainy** [CalciferZh/SMPL#17]
Thank you for your job, I am reading the paper now.
I know the pose parameters represent the rotation vectors of joints,
But I didn't find the specific meaning of the shape parameters. There are ten of them, would you please tell me what's the specific meaning of them? (like weight, height?)
Thank you very much.

**Comment by sebftw** [comment]
They are multiplied onto the orthonormal principal components of shape displacements, who are then added onto the base shape `v_template`.

Assuming beta.shape = (10), shapedirs.shape = (N, 3, 10) and v_template.shape = (N, 3) the relation can be written as `v_shaped = (beta * shapedirs).sum(dim=-1) + v_template`.
Here `v_template` is the average of the body shapes used to create the model.
And `shapedirs` are the orthonormal shape displacements.

They are constrained to being orthogonal which makes it easy to recover the betas given the vertices but means there is not likely a simple interpretation. They come in order of significance, which I think is shown in Figure 9 of the paper.
![image](https://user-images.githubusercontent.com/5397919/57242626-4cc37900-7034-11e9-9c91-b4a24cf7cf6f.png)

It looks like 90% of the variance is explained by the first shape parameter, `beta[0]` and then the second parameter explains the next 10 % and so on. This is not uncommon with this kind of decomposition. It is very likely the first few shape parameters do correlate with weight and/or height like you said.

For more details you can look up principal component analysis.

**Comment by YoungRainy** [comment]
@sebftw Thank you so much!
So, do you mean the shape parameters are computed by using PCA to the hand model? 
Not as what I thought before, the parameters are chosen manually.

**Comment by sebftw** [comment]
Yes. The PCA is applied to some model to get its shape parameters.
The method works in both directions, so if you have `v_shaped` you can compute `beta` and vica versa.
But if you take a mesh from the real world you will have some loss of details, which is quantified by the cumulative relative variance in Figure 9. Going from `beta` to `v_shaped` and back to `beta` is lossless though.

**Comment by YoungRainy** [comment]
@sebftw Thank you so much.

**Comment by olga-2020-Feb** [comment]
Thank you for your job from me too. 
I have question about the count of shape parameters (betas). In your code there are 10 of them, but in this paper they say they are using 50 shape parameters. 

https://ps.is.tuebingen.mpg.de/uploads_file/attachment/attachment/374/clothcap.pdf

Is it possible? If yes could you please give me a hint how?
Thank you very much.

**Comment by CalciferZh** [comment]
I _guess_ they do have 50 shape parameters, but only release 10 of them to the public.

**Comment by olga-2020-Feb** [comment]
Thank you!

**Comment by sparshgarg23** [comment]
I have seen in this repository as well as other repos where SMPL is being used that beta is initally set to a random vector.So is beta generally set to random.
What if we wanted to fit SMPL on an image,how do we go about extracting the shape parameters from a new 3d scan of a human body or an image
I know that pose can be esitmated using OpenPose/Dense pose but I am not clear about how to find the shape parameters
