### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'tensordot'

### ISSUE THREAD

**Issue by AlexM30** [CalciferZh/SMPL#21]
File "smpl_torch.py", line 132, in forward
    v_shaped = torch.tensordot(self.shapedirs, betas, dims=([2], [0])) + self.v_template
AttributeError: module 'torch' has no attribute 'tensordot'

Any ideas why and how could this be fixed?

**Comment by sebftw** [comment]
You must update PyTorch. [Link.](https://pytorch.org/get-started/locally/)
