### ISSUE TITLE
Why is the arm always flat?

### ISSUE THREAD

**Issue by Yedis** [CalciferZh/SMPL#24]
@CalciferZh 
I run your code but find the arms are always flat.
Is this right?

**Comment by CalciferZh** [comment]
I don't really get what "flat" means. Could you provide some visualization of "flat" arms? A screenshot of the mesh would be great =)

**Comment by Yedis** [comment]
![Selection_041](https://user-images.githubusercontent.com/31688580/61592599-f95ed100-ac07-11e9-8cb6-370bd5e0da99.png)

**Comment by CalciferZh** [comment]
On one hand, seems that it's not strictly "flat"; on the other hand, did you try to set some radical parameters for the arms to see how everything works?

**Comment by Yedis** [comment]
My bad. I haven't do that yet. Maybe I'd better have a try. 
Are things going well in your testing?
