### ISSUE TITLE
question about how to convert parms info to numpy

### ISSUE THREAD

**Issue by liwenssss** [CalciferZh/SMPL#25]
hello, thanks your great job that help me .But when I use the pytorch version SMPL,I find some conflict. FOr example:
`
self.shapedirs = torch.from_numpy(params['shapedirs']).type(torch.float64)
`
I got:
`
TypeError: expected np.ndarray (got Ch)
`
There still many like this. I want to know is it the version of my environment that cause the problem. And if we can have a conversion offline or by email.
Thx your great job again~

**Comment by CalciferZh** [comment]
Did you run `preprocess.py` first to convert the official model?

**Comment by liwenssss** [comment]
> Did you run `preprocess.py` first to convert the official model?

ops, I just run the pytorch version. THx your quick reply! 
By the way,  is any interface to get vert and joint, not the final res.
Thanks your quick reply again!

**Comment by CalciferZh** [comment]
For vertices see `SMPLModel.verts`, for joints see [this issue](https://github.com/CalciferZh/SMPL/issues/22)
