### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by OOF-dura** [CalciferZh/SMPL#28]
I noticed that there are joints information in the implementation version of the pytorch batch, and these parameters are not available in the model provided by SMPL. Where is this model? Thank you!

**Comment by OOF-dura** [comment]
I also noticed that in preprocess.py there is a choice "cocoplus_regressor" but I didn't find it in the model file.

**Comment by CalciferZh** [comment]
That's about SMIL model. I think you can simply ignore it.
