### ISSUE TITLE
How to calculate pose parameter

### ISSUE THREAD

**Issue by ffiioonnaa** [CalciferZh/SMPL#29]
Thanks for your work about SMPL. I'm a beginner of human modeling, and I have a question about how to get the pose parameter given a set of  joints  coordinate coefficient . Is it that  calculating the angle between to adjacent bones and represent it in terms of axis-angle as the pose parameter? Do I need to substract the rest pose? Could you please provide a  detailed calculation steps

**Comment by CalciferZh** [comment]
Seems that you can check the concept "inverse kinematic fitting" first.

**Comment by HenriMir** [comment]
@ffiioonnaa Hi, did you manage to solve your issue? We are having the same problem

Thanks for any help
