### ISSUE TITLE
For batch input

### ISSUE THREAD

**Issue by xiaozai** [CalciferZh/SMPL#3]
Hi, Thanks for your SMPL_in_TF, which is very useful. 
I tried the code and it works very well. but one thing is dimension error when the input is batch files. I used your code in the CNN network and my input is [N, 10] for betas, now I use the tf.while_loops to solve this problem. Maybe later we could consider to improve it for batch inputs. Thanks again for your code

**Comment by CalciferZh** [comment]
Thanks for your suggestion! I'm afraid I don't have time to add new features recently. Sorry about that =(
