### ISSUE TITLE
When running the smpl_torch_batch.py in the google colaboratory enviroment, I encounter a problem. 

### ISSUE THREAD

**Issue by hcp6897** [CalciferZh/SMPL#31]
When running the smpl_torch_batch.py in the google colaboratory enviroment, I encounter a problem. 
command1:
**!python3  smpl_torch_batch.py**
error1:
Traceback (most recent call last):
  File "smpl_torch_batch.py", line 228, in <module>
    test_gpu([1])
  File "smpl_torch_batch.py", line 211, in test_gpu
    model = SMPLModel(device=device)
  File "smpl_torch_batch.py", line 18, in __init__
    **np.array(params['joint_regressor'].T.todense())
KeyError: 'joint_regressor'**

cmmand2:
**!python3 SMIL_torch_batch.py**

error2:
**Traceback (most recent call last):
  File "SMIL_torch_batch.py", line 217, in <module>
    from smil_np import SMILModel
ModuleNotFoundError: No module named 'smil_np'**

**Comment by CalciferZh** [comment]
Should be fixed now. Apologize for the late response.
