### ISSUE TITLE
What is the range of normalization?

### ISSUE THREAD

**Issue by pacifinapacific** [CalciferZh/SMPL#33]
Thank you for your useful code
In smpl_np.py, I do not know the range of normalization such as pose information
I'm sorry to trouble you, but could I ask you to do this for me?

**Comment by CalciferZh** [comment]
Sorry, but I don't exactly understand your meaning by "range of normalization".
If you mean the range of the parameters:
* for pose it has clear meaning - the rotation for each joint in axis-angle representation;
* for shape I'm not sure, typically I would say [-3,3] would be fine (as the three-sigma rule)

**Comment by pacifinapacific** [comment]
If I try to rotate one angle by 90 degrees, can I achieve that by adding π / 2 to the pose array?

**Comment by CalciferZh** [comment]
Have you checked the concepts such as rotation matrix and axis-angle?

**Comment by pacifinapacific** [comment]
I seem to be short of studying.
Sorry for bothering you
