### ISSUE TITLE
Sorry to bother you. would you please help me solve this error?

### ISSUE THREAD

**Issue by OldChi** [CalciferZh/SMPL#34]
(SMPL) huangxinkai@ubuntu:~/project/SMPL$ python preprocess.py smpl/models/basic             Model_f_lbs_10_207_0_v1.0.0.pkl
(SMPL) huangxinkai@ubuntu:~/project/SMPL$ python preprocess.py smpl/models/basic             model_m_lbs_10_207_0_v1.0.0.pkl
(SMPL) huangxinkai@ubuntu:~/project/SMPL$ python smpl_torch.py
cuda
(SMPL) huangxinkai@ubuntu:~/project/SMPL$ python smpl_torch_batch.py
Traceback (most recent call last):
  File "smpl_torch_batch.py", line 228, in <module>
    test_gpu([1])
  File "smpl_torch_batch.py", line 211, in test_gpu
    model = SMPLModel(device=device)
  File "smpl_torch_batch.py", line 18, in __init__
    np.array(params['joint_regressor'].T.todense())
KeyError: 'joint_regressor'

I find nothing after running python smpl_torch.py and an error occur after running python smpl_torch_batch.py.

here's my package list:
Package    Version
---------- -------
chumpy     0.69
numpy      1.17.3
pip        19.3.1
scipy      1.3.1
setuptools 41.6.0
six        1.12.0
torch      1.0.0
wheel      0.33.6

my python vision is 3.6

**Comment by CalciferZh** [comment]
Should be fixed now. Apologize for the late response.
