### ISSUE TITLE
Pose parameters to joint rotation?

### ISSUE THREAD

**Issue by HelloEgg** [CalciferZh/SMPL#35]
Hi.

Thanks for the great work.

I am trying to export result to Unity humanoid rig.

After running SMPL, I got 24*3=72 pose parameters.

How would I be able to change these parameters to joint rotations of rig? 

From my understanding, pose parameters seem to be axis-angle.

Converting axis-angle requires an angle, theta, along with x y z vectors which are pose parameters of SMPL.

Pose parameters I got were mostly in range of [-1,1] which is unlikely to be Euler degree...

Would anyone have good idea to solve this?

Thank you

**Comment by CalciferZh** [comment]
I'm not quite sure if I understand what you mean. The pose parameter is represented as axis-angle rotations of each joint. Converting rotations from axis-angle representation to Euler angle representation should be trivial.

**Comment by HelloEgg** [comment]
@CalciferZh  Thank you!

From my understanding, axis-angle representation is given as (x,y,z,θ(angle)).

Are the result pose parameters x*θ, y*θ, z*θ ?

Are they radians? or degrees?

Thank you very much!

**Comment by CalciferZh** [comment]
Yes it's xθ, yθ, zθ in radian. Gook luck :)

**Comment by HelloEgg** [comment]
Hi! One last question...

I converted axis angle to euler angles with following code :

`from scipy.spatial.transform import Rotation as R`
`r = R.from_rotvec(rotationalVector)`
`euler = r.as_euler('xyz', degrees=True)`

**Which turns axis-angle** 

[-9.5697e-03,  1.2608e-03, -3.6732e-02],
       [-7.3293e-02, -2.3585e-02, -7.1762e-02],
       [ 2.6486e-01,  8.2785e-03,  5.1119e-02],
       [-6.0913e-02,  1.2531e-02,  6.8015e-02],
       [-1.6504e-02,  2.7714e-02, -8.0994e-02],
       [ 1.3821e-01, -3.7714e-02, -2.3450e-02],
       [-1.9392e-01,  2.0978e-01,  3.5516e-02],
       [-2.0094e-01, -1.3046e-01,  3.6982e-02],
       [-1.6031e-01,  4.5346e-02, -7.0002e-03],
       [ 2.6784e-02,  2.5078e-02,  1.1088e-02],
       [ 1.6434e-02,  9.7315e-03, -2.9229e-03],
       [ 2.6557e-01, -9.1501e-02, -1.4613e-01],
       [-5.0732e-02, -2.4710e-01, -1.3759e-01],
       [-1.9761e-02,  4.8839e-01,  3.4859e-02],
       [-4.2612e-01, -3.1323e-02,  9.5838e-02],
       [-5.1245e-02, -2.7034e-01, -7.5090e-01],
       [-2.4096e-01,  5.0958e-01,  6.1130e-01],
       [-5.3572e-01, -1.5739e+00,  1.5361e-01],
       [-8.4502e-02,  1.2916e+00, -6.6262e-01],
       [-7.0108e-01, -3.0010e-01, -2.5804e-01],
       [ 2.0571e-01,  2.6393e-01, -4.7471e-01]

**To following Euler angle:**

[-0.54950694  0.06215224 -2.10490296]
[-4.14823094 -1.49953745 -4.05938132]
[15.18088447  0.08306021  2.95722918]
[-3.46319674  0.83559128  3.87296712]
[-1.00909676  1.54780269 -4.65464781]
[ 7.94693676 -2.06103018 -1.48906632]
[-11.06040504  12.14077437   0.86900997]
[-11.71144351  -7.20897234   2.86941649]
[-9.20024554  2.55488344 -0.60761258]
[1.54286506 1.42815278 0.65459775]
[ 0.94081245  0.55892411 -0.16288594]
[15.57247799 -4.05634525 -8.982945  ]
[ -1.96080961 -14.31069834  -7.67917723]
[-0.69018935 27.99631108  1.86594761]
[-24.46461055  -0.58651862   5.703321  ]
[  2.98349699 -15.10965752 -43.68496402]
[-4.51681426 31.49049145 34.68971092]
[-102.16905612  -64.90605815   88.05278959]
[-54.16967679  59.18239213 -76.52187676]
[-39.2063174  -20.75593328  -8.07905307]
[  8.03229387  17.26604476 -26.2311498 ]

I manually rotated each humanoid joints in Unity humanoid rig, however, result is not same as SMPL render result. 

I assumed each element order as SMPL joint order. That is,

[Pelvis, LHip, RHip, Spine,LKnee, RKnee, Spine 2, etc...]

Have I translated axis-angle to Euler with wrong method? or is there another step before I apply

euler degrees to humanoid rig?

Thank you very much for sharing your time!

Best regards

**Comment by CalciferZh** [comment]
I'm not very familiar with Unity. One possible reason is that in SMPL the axes are **relative** instead of **global**. For example, when you move arm first, the hand would move with arm and the xyz axes of hand do not equal to world xyz anymore. I'm not sure if Unity also take care of this change of coordinate system.

**Comment by HelloEgg** [comment]
@CalciferZh 
Thank you for your kind reply!

With your advice on xyz axes, I converterd axis-angle to quaternion using 
```

from scipy.spatial.transform import Rotation as R
r = R.from_rotvec(rotationalVector)
euler = r.as_quat()
```
which, I believe, is irrelevant to xyz orientation...  

However, resulting humanoid rig still yields wierd pose...

would rotating order matter too?

I mean, rotating shoulder first and wrist at second would yield different result from 
rotating wrist first and then shoulder?

Thank you!

**Comment by CalciferZh** [comment]
I'm not sure how Unity handle this, but rotating order _might_ matter.

**Comment by acoMCMXCVI** [comment]
@HelloEgg did you find solution for your issue? I also trying to find way how to use pose parameters to make pose in engine or some other 3d software. 

Thank you

**Comment by benMOOVENCY** [comment]
@acoMCMXCVI  @HelloEgg , did you find solution for this issue ? I also trying to find way to transform pose parameters to global orientation for each joint idealy in Quaternion ? 

Thank you

**Comment by HelloEgg** [comment]
@acoMCMXCVI @benMOOVENCY Hi. Sorry for late reply. I made a pipeline that inputs pose parameters, and project it to VPoser. The VPoser then outputs local rotations of each joints. I'm not sure if the VPoser can produce global rotation. 
In case the VPoser can't produce global rotation, you can try injecting local rotation to unity SMPL model which was released couple of weeks ago. Then, you can try extracting global rotation. 
XYZ directions are different for some joints between VPoser local joints and Unity SMPL model.
I am thinking of making a repo on github for data pipeline of SMPL -  VPoser - Unity if many people need it (and authors of SMPL allow me)

**Comment by benMOOVENCY** [comment]
@HelloEgg  thanks you for this answer, yes a github repo could be a good help for us.

**Comment by vivi90** [comment]
@HelloEgg
> [..] With your advice on xyz axes, I converterd axis-angle to quaternion using
> 
> ```
> from scipy.spatial.transform import Rotation as R
> r = R.from_rotvec(rotationalVector)
> euler = r.as_quat()
> ```
> [..]

Thank you^^
