### ISSUE TITLE
Conversion between cartesian coordinates and axis-angle representations

### ISSUE THREAD

**Issue by dbgns** [CalciferZh/SMPL#36]
Thanks for the great work! 
I am trying to understand the code and I have some problems which have confused me for a long time 
* How can I get the transformation matrix for specific joints? When we are computing the new location for a specific joint, it seems that if we unroll the matrix multipication [here](https://github.com/CalciferZh/SMPL/blob/master/smpl_torch.py#L155)(take pytorch code for example), the rotation matrix for current joint of interest is not included(only rotation matrices from ancestors are included), it that correct? 
These are formulas from original paper: 
![image](https://user-images.githubusercontent.com/37951601/73661348-e0fe6180-46d4-11ea-813a-191ff3f08766.png)
* In SMPL conversion from axis-angle representations to cartesian cooridinates are included implicity(theta -> R -> J), what about the other direction? If we have joints in the format of (x, y, z), how can we get the axis-angle/euler-angle representations? 

I am not an english native speaker, so I am sorry for my terrible and abstract expression... appreciate for any help :)

**Comment by CalciferZh** [comment]
* The position of one joint is determined by its ancestors and irrelevant to the rotation itself. It's like if you keep your arm fixed your wrist will not move however it rotates.
* You can check the idea of "inverse kinematics".
Be confident, your English is clear enough :)

**Comment by dbgns** [comment]
If I keep my elbow fixed, the rotation of the wrist will affect its coordinates, won't it?

**Comment by CalciferZh** [comment]
Why? The rotation of wrist will only affect hand. The rotation of elbow is actually the rotation of the bone between elbow and wrist.

**Comment by dbgns** [comment]
Oh... I got it( I thought the rotation of elbow is the rotation of the bone between shoulder and elbow...).. But in this way, how the depict the rotation of joints that have multiple children?

**Comment by CalciferZh** [comment]
Yes you find the flaw of this formulation. The bones that share the same parent cannot move individually. They have to move together. In practice this approximation is okay because usually those bones cannot even move. For instance the bones from pelvis to to left and right hip.

**Comment by dbgns** [comment]
Got it, thanks a lot!

**Comment by dbgns** [comment]
Sorry , I have another question: when removing the transformation due to the rest pose(actually, I think this is computing the displacement of joints and then apply to the vertices?), why the code [here](https://github.com/CalciferZh/SMPL/blob/master/smpl_torch.py#L166) is like this? I think the `stacked` here includes rotation matrix itself along with matrices from ancestors. It seems that this is different from the case mentioned above? why?

**Comment by CalciferZh** [comment]
https://github.com/CalciferZh/SMPL/issues/32 would this be helpful?

**Comment by dbgns** [comment]
I saw this issue, but I still can not understand... Do you mean `linear blend skinning`?

**Comment by CalciferZh** [comment]
That's right.

**Comment by dbgns** [comment]
All right, I will try to figure it out... thanks!

**Comment by antoinedelplace** [comment]
Hello @FishWoWater ,
Have you succeeded in converting 3D joints positions into pose rotations ?
I cannot figure this out !

**Comment by FishWoWater** [comment]
@antoinedelplace 
You can refer to inverse kinematics solver like https://github.com/CalciferZh/Minimal-IK
