### ISSUE TITLE
Vertex index of specifc part of human

### ISSUE THREAD

**Issue by dbgns** [CalciferZh/SMPL#38]
Hi! Do you know how to get the indices of vertices that belong to a specific part of human? I know there are 24 parts and 6890 vertices but don't know how to match them. Thanks!!!!!!!!!!!!!!

**Comment by CalciferZh** [comment]
Sorry but for now I don't have any good idea for that.

**Comment by dbgns** [comment]
thank you, any way, and sorry for always disturbing you, I am too cai
