### ISSUE TITLE
What does these codes mean in smpl_tf.py line 148 ?

### ISSUE THREAD

**Issue by Chang-Che-Kuei** [CalciferZh/SMPL#39]
I had thought about it for hours but didn't get it.
Please help me understand it.

`` results = stacked - \
            pack(
              tf.matmul(
                stacked,
                tf.reshape(
                  tf.concat((J, tf.zeros((24, 1), dtype=tf.float64)), axis=1),
                  (24, 4, 1)
                )
              )
            )``

**Comment by CalciferZh** [comment]
You may check ‘smpl.np’ for more comments. The corresponding equation can be found in the paper. It’s just a basic linear blend skinning.
