### ISSUE TITLE
why use axis-angle rather than euler

### ISSUE THREAD

**Issue by ffiioonnaa** [CalciferZh/SMPL#41]
Hi, I have a question that why smpl choose axis-angle representation? Cause I find I can't rotate the part to a position that I want by giving angles, why don't use euler angle? Euler seems more intuitional. Are there any other considerations?

**Comment by CalciferZh** [comment]
I think axis-angle is more concise. For euler angles you need to define the rotation order, which may introduce some ambiguity, I guess.

**Comment by ffiioonnaa** [comment]
Thanks~and why don't use quaternion?

**Comment by CalciferZh** [comment]
Maybe then axis-angel is Intuitive ; )

**Comment by ffiioonnaa** [comment]
okay，thanks~，I‘ll close this issue
