### ISSUE TITLE
Joints corresponding to smpl vertices

### ISSUE THREAD

**Issue by moondabaojian** [CalciferZh/SMPL#43]
Hello! Thank you for your great work?
Do you know how to get the joints corresponding to the vertices of smpl？
I know that I can get joint points from vertices through ‘J_regressor’ matrix
But how do you know which joint a vertex is bound to? Or the vertex is bound to multiple joint points, which joint point has the most weight？

**Comment by CalciferZh** [comment]
That should be  `params['weights']`.

**Comment by moondabaojian** [comment]
Thank you for your answer. I know this parameter, but it should not be what I want. I have found a solution

**Comment by CalciferZh** [comment]
ok, good luck :)
