### ISSUE TITLE
SMPL augmentation: how to rotate a whole SMPL sequence

### ISSUE THREAD

**Issue by khanhha** [CalciferZh/SMPL#46]
Hello, 
It's a bit out off-topic here, but could you please show me how to rotate a temporal SMPL sequence along the z axis? 
Specifically, we have an SMPL animation that consists of N translation and global rotation. Can you suggest me how to rotate the whole animation by an angle along the Z-axis? 
Do need to rotate both translation and the global rotation simultaneously with the same rotation matrix?
Thanks

**Comment by CalciferZh** [comment]
Yes I think so, if I understand you correctly :)
