### ISSUE TITLE
Error in computing v_shaped

### ISSUE THREAD

**Issue by lafith** [CalciferZh/SMPL#49]
hi,

I ran preprocess.py on the model 'basicModel_m_lbs_10_207_0_v1.1.0.pkl' from the download link as mentioned in README.
But when I ran smpl_np.py it is giving following error:

![Screenshot from 2020-10-15 19-14-12](https://user-images.githubusercontent.com/39316548/96137837-c2669080-0f1a-11eb-95c1-3d2107070999.png)

Error is in calculation of v_shaped, line 88 of smpl_np.py

**Comment by CalciferZh** [comment]
I think that's because are using the version with 300 shape PCA bases. You can either shrink shapedirs to [6890, 3, 10] or expand beta to [300]

**Comment by lafith** [comment]
ok, its working. Thanks!
