### ISSUE TITLE
How to get UV coordinates for the template

### ISSUE THREAD

**Issue by ypflll** [CalciferZh/SMPL#5]
I want to represent a SMPL model in 2d form like this which is from zbrush:
![image](https://user-images.githubusercontent.com/12528364/45752552-6bf9cb80-bc48-11e8-903a-bceb3c0cbc3c.png)

How can get the UV coordinates for SMPL model ?

**Comment by VVingerfly** [comment]
@ypflll You can cut the mesh first，then use a parametrization method to compute the 2d uv coordinates.

**Comment by VVingerfly** [comment]
@ypflll DensePose provides a segmentation and also 2d uv coordiantes, but the mesh is segmented into 24 parts. You can have a look.

**Comment by ypflll** [comment]
@VVingerfly Thank you for reply.

Densepose do uses uv coord, however, they never say how to generate it or provide the data. We have some discussion here: https://github.com/facebookresearch/DensePose/issues/116

I've managed to use autodesk's fbx-sdk get the uv map included in SMPL .fbx file, like this:
![image](https://user-images.githubusercontent.com/12528364/46777697-f4005c00-cd42-11e8-9b68-80b3eb7a5797.png)


This is segmented into many parts, and not fill the whole image.
The right uv map I want is continous(like the first image above) and it would be best to fill as many as part of the image.
So some 3d software like blender or zbrush can do this? I've tried a little, but seems very complicated for me. It will be great help if you can provide more infomation or some details on how to cut mesh or do parametrization.

**Comment by VVingerfly** [comment]
@ypflll the uv data of DensePose can be found [here](https://github.com/facebookresearch/DensePose/blob/master/DensePoseData/get_densepose_uv.sh)

If you want generate new uv coordinates, you need to cut the mesh first, 
then using a mesh parametrization method like [LSCM](https://members.loria.fr/Bruno.Levy/papers/LSCM_SIGGRAPH_2002.pdf) to flatten the mesh.

**Comment by ypflll** [comment]
@VVingerfly I think using software like blender or zbrush will be a easier way. I'll try it later.

**Comment by Lotayou** [comment]
@ypflll Hi, can you share the UV map mentioned [above](https://github.com/CalciferZh/SMPL/issues/5#issuecomment-428801654) with me? A 6890*2 matrix would be nice, thx!

**Comment by Dolorousrtur** [comment]
@Lotayou and everyone interested,
uploaded it to Google Drive: https://drive.google.com/open?id=1i5DiaFsik7WcvfQwwIXcdj2LRxmTDqgG

**Comment by mlyarthur** [comment]
> @VVingerfly I think using software like blender or zbrush will be a easier way. I'll try it later.

Sorry to bother .I want to know have you got the uv map of the smpl-x model, for now the original project still cannot supply one

**Comment by mwang259** [comment]
> @VVingerfly Thank you for reply.
> 
> Densepose do uses uv coord, however, they never say how to generate it or provide the data. We have some discussion here: [facebookresearch/DensePose#116](https://github.com/facebookresearch/DensePose/issues/116)
> 
> I've managed to use autodesk's fbx-sdk get the uv map included in SMPL .fbx file, like this: ![image](https://user-images.githubusercontent.com/12528364/46777697-f4005c00-cd42-11e8-9b68-80b3eb7a5797.png)
> 
> This is segmented into many parts, and not fill the whole image. The right uv map I want is continous(like the first image above) and it would be best to fill as many as part of the image. So some 3d software like blender or zbrush can do this? I've tried a little, but seems very complicated for me. It will be great help if you can provide more infomation or some details on how to cut mesh or do parametrization.


Hi, I am working for texture coordinates, could you share the UV map mentioned [above](https://github.com/CalciferZh/SMPL/issues/5#issuecomment-428801654) , I really need your help, thanks!

**Comment by mwang259** [comment]
@ypflll Hi, I am working for texture coordinates, could you share the UV map mentioned https://github.com/CalciferZh/SMPL/issues/5#issuecomment-428801654 , I really need your help, thanks!

**Comment by mwang259** [comment]
@Dolorousrtur  Hi, the Google Drive link is not available, could share this link again? thanks!
