### ISSUE TITLE
obj model upside down when pose and beta are given from SMPLify.

### ISSUE THREAD

**Issue by lafith** [CalciferZh/SMPL#50]
Hello,

I used pose and beta from a model file generated by SMPLify. But when the obj file is opened in blender its not face up.

- **model file** : [m1.zip](https://github.com/CalciferZh/SMPL/files/5395621/m1.zip)
- **obj opened in Blender**:  [m1_obj.zip](https://github.com/CalciferZh/SMPL/files/5395626/m1_obj.zip)

![Screenshot from 2020-10-17 17-57-56](https://user-images.githubusercontent.com/39316548/96337142-6595e200-10a2-11eb-8f64-27d7f0578f64.png)

I used smpl_np.py:

![Screenshot from 2020-10-17 18-00-15](https://user-images.githubusercontent.com/39316548/96337200-c8877900-10a2-11eb-86d2-4ab79b934639.png)

**Comment by lafith** [comment]
Is there any part in your code that can be change to rotate the pose by some angle?

**Comment by sebftw** [comment]
The first three numbers in the pose is the global rotation, so you can change the pose rotation by modifying these.

I think you can also fix the problem in the import dialogue in Blender, by changing the Up vector to **-Y up**:

![image](https://user-images.githubusercontent.com/5397919/96371279-2da1a400-1161-11eb-831c-241ff44b41e8.png)
