### ISSUE TITLE
joint positions after pose

### ISSUE THREAD

**Issue by cuiyuexin** [CalciferZh/SMPL#51]
Thank you for this great implementation of SMPL!

Now I have a question. I wonder how to calculate joint positions after applying specific pose. In SMPL paper, we can calculate joint positions of rest pose using J_regressor matrix. And I think posed joint positions should be obtained by applying joint transformation matrix (equation 3 in SMPL paper) to rest pose joint positions, instead of directly using J_regressor to vertices after Linear Blend Skinning. Can you give me some hint on this question?

**Comment by CalciferZh** [comment]
Yes, using J_regressor to vertices after LBS is okay but not most accurate.
Joint positions is actually easier: 
1) you need to compute the rotation of each bone and apply it to that bone, rotating around the parent joint
2) then you can infer the position of the child joint after posing according to the rotated bone vector and the coordinate of the parent joint
3) you can do this along the kinematic chain to get the position of all joints
That's done in https://github.com/CalciferZh/SMPL/blob/master/smpl_np.py#L102   and G partially contains the result.

**Comment by cuiyuexin** [comment]
I really appreciate your kindly help!

In my opinion, the joint positions are actually contained in the last column of the corresponding transformation matrix. Thank you!
