### ISSUE TITLE
Question: What mean the parameters in test.py

### ISSUE THREAD

**Issue by neoglez** [CalciferZh/SMPL#52]
In test.py https://github.com/CalciferZh/SMPL/blob/3a572a6672eee6ab2ca832374ee14bd286744426/test.py#L58-L59 we see that both shape and pose are being centered (subtract mean = 1/2 = 0.5) and also multiplied by (somehow) arbitrary numbers (scale).

What does 0.4 and 0.06 mean in this context? Are they really arbitrary or is there and intuitive interpretation?
Thanks in advance.

**Comment by CalciferZh** [comment]
They are just arbitrary.
