### ISSUE TITLE
Difference between the SMPL's Rodrigues formula and yours

### ISSUE THREAD

**Issue by wangfudong** [CalciferZh/SMPL#54]
Hi,
In the paper of SMPL, the Rodrigues formula is used as:
![image](https://user-images.githubusercontent.com/23078915/103271411-2d414700-49f5-11eb-9aab-909e712c2826.png)
 
However, in your `smpl_np.py`, I find that,

`R = cos * i_cube + (1 - cos) * dot + np.sin(theta) * m`  **(2)**
 By converting these mathematical notations in **(2)**, **(2)** can be rewritten as:
![image](https://user-images.githubusercontent.com/23078915/103272144-071ca680-49f7-11eb-9bdd-57b8ac84e6ab.png)
 
And,  to my knowledge about Rodrigues formula (e.g., https://en.wikipedia.org/wiki/Rodrigues%27_rotation_formula), 
it should be written as the formula of yours, not as the formula used in SMPL paper, right?

**Comment by CalciferZh** [comment]
Yes I guess it's some typo in the original paper.
