### ISSUE TITLE
SMPL : 3D joints positions to pose rotations

### ISSUE THREAD

**Issue by antoinedelplace** [CalciferZh/SMPL#55]
Hi,

I am trying to convert 3D joints positions to pose rotations in order to create a SMPL model from these positions.

In the SMPL paper, it is said : "The pose of the body is defined by a standard skeletal rig, where w_k denotes the axis-angle representation of the relative rotation of part k with respect to its parent in the kinematic tree."

I have tried to compute the axis and the angle of each joint with respect to its parents but without success. The method is however simple : if J is the joint position, P the parent position and G the grandparent position, then
axis = GP x PJ
angle = arccos(GP.PJ / (norm(GP).norm(PJ))

To have the angle-axis, I normalise axis and do normalized_axis x angle.

What am I doing wrong ? Should I use a t-pose to find the good poses ?

**Comment by CalciferZh** [comment]
Hi, I think this is not the correct way to compute axis-angle from joint positions. You can search the concept "inverse kinematics" which may be helpful.
