### ISSUE TITLE
SMPL joint names and its indexes

### ISSUE THREAD

**Issue by anilkunchalaece** [CalciferZh/SMPL#56]
Hi,

Could you please specify SMPL joint indexes and its names ?

**Comment by CalciferZh** [comment]
'pelvis',
    'left leg root', 'right leg root',
    'lowerback',
    'left knee', 'right knee',
    'upperback',
    'left ankle', 'right ankle',
    'thorax',
    'left toes', 'right toes',
    'lowerneck',
    'left clavicle', 'right clavicle',
    'upperneck',
    'left armroot', 'right armroot',
    'left elbow', 'right elbow',
    'left wrist', 'right wrist',
    'left hand', 'right hand'

**Comment by anilkunchalaece** [comment]
Thanks

**Comment by anilkunchalaece** [comment]
What is the scale of joints ? is it ( -1, 1) or something else. 
Can you please provide example on how to visualize joints on image ?

**Comment by CalciferZh** [comment]
The unit is meter.
