### ISSUE TITLE
obtain SMPL parameters from .obj files

### ISSUE THREAD

**Issue by akchain** [CalciferZh/SMPL#58]
Hi, I can generate .obj files from SMPL parameters and my question is how can I get these parameters given a .obj file? I failed to find any solution to it. Any help is greatly appreciated.

**Comment by vra** [comment]
Hi @akchain , did you find a solution for this question?

**Comment by CalciferZh** [comment]
This might be helpful: https://en.wikipedia.org/wiki/Inverse_kinematics
