### ISSUE TITLE
Training  get error

### ISSUE THREAD

**Issue by caijinana** [CalciferZh/SMPL#64]
![微信图片_20220308153627](https://user-images.githubusercontent.com/64821543/157189021-ad3604f8-96c7-4471-b647-f94f7ece875c.png)
Hello ,Dear    professor:
when i training the code,i got the error as the picture,but i can training the code in the morning,but when i training 1 epoch, i got the error, i used training the code successfully in the january.Can you help me?

**Comment by CalciferZh** [comment]
You are running out of memory.
BTW are you sure you are using this repo?
