### ISSUE TITLE
nan in smpl_np

### ISSUE THREAD

**Issue by snitchjinx** [CalciferZh/SMPL#65]
Hello! I encountered an outlier when using numpy version of SMPL. Specifically, the output of v_shape becomes all nan:
`v_posed = v_shaped + self.posedirs.dot(lrotmin)`
However, the same pose works fine on the original SMPL with chumpy.
I wonder if this is caused by some mechanisms of np.dot on very small number? 

Below are my pose data and some scripts I used:
```
data = np.load("./poses_from_ROMP.npz",allow_pickle=True)['results'][()]
key_list = list(data)
poses = data[key_list[1]][0]
rotation = poses['pose'][0].copy()
m.set_params(pose = rotation)
```
then m.verts become all nan.

[poses_from_ROMP.zip](https://github.com/CalciferZh/SMPL/files/8204206/poses_from_ROMP.zip)

**Comment by CalciferZh** [comment]
Hi, many thanks for the feedback. It is because the input pose is in `float16`. It has been fixed now.
You can fix it yourself by changing line 137 to `theta = np.maximum(theta, np.finfo(r.dtype).eps)`

**Comment by snitchjinx** [comment]
> Hi, many thanks for the feedback. It is because the input pose is in `float16`. It has been fixed now. You can fix it yourself by changing line 137 to `theta = np.maximum(theta, np.finfo(r.dtype).eps)`

Cool!
