### ISSUE TITLE
smooth smpl model

### ISSUE THREAD

**Issue by AhmadNashaat0** [CalciferZh/SMPL#66]
output obj from smpl has triangle faces, is there any way to smooth it ? 
like making smooth shading to the model in blender

**Comment by CalciferZh** [comment]
I think it's you should use the right rendering option. It's not about the mesh itself.

**Comment by AhmadNashaat0** [comment]
i have low experience in this domain can you help me and show me the right tools to do it

**Comment by CalciferZh** [comment]
They are two separate things: mesh and rendering. There is no easy way to make the mesh "smooth". You can make it looks smooth with the right rendering options, and the options depend on the tool you use to render the mesh, e.g. MeshLab, or Blender, or Unity, etc.

**Comment by AhmadNashaat0** [comment]
thank you <3
