### ISSUE TITLE
Downloading model

### ISSUE THREAD

**Issue by JosephKKim** [CalciferZh/SMPL#67]
I can't go to the link you've provided in readme.
Can you renew the link? 
Thanks for the work!

**Comment by CalciferZh** [comment]
Updated. Thanks for reminding.

**Comment by zhangsanfeng86** [comment]
Hi @CalciferZh 
after register， where is the download link ?
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/73547638/160554418-32447b95-ec6f-4ddb-bf55-2c327c994a34.png">
