### ISSUE TITLE
load smpl model Error

### ISSUE THREAD

**Issue by zhangsanfeng86** [CalciferZh/SMPL#68]
@CalciferZh ,Thank you for release!
when load smpl model got Error:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/73547638/161287681-91b13054-b89e-4c1c-82a0-8b45c9b36865.png">

**Comment by CalciferZh** [comment]
This is because you are using a different SMPL version with 300 shape coefficients instead of 10. Changing https://github.com/CalciferZh/SMPL/blob/master/smpl_np.py#L23 to `self.shapedirs = params['shapedirs'][..., :10]` might fix this.

**Comment by zhangsanfeng86** [comment]
@CalciferZh Thank you for ur quick reply!
it done!
