### ISSUE TITLE
How to conver 'keypoints3d' to 'smpl_poses' and 'smpl_trans' ?

### ISSUE THREAD

**Issue by zhangsanfeng86** [CalciferZh/SMPL#69]
Hi @CalciferZh 
Thank you for your wonderful work!

With the help of your code , 'smpl_poses' and 'smpl_trans' conver to 'keypoints3d' .
But How to conver 'keypoints3d' to 'smpl_poses' and 'smpl_trans' ?

**Comment by CalciferZh** [comment]
https://github.com/CalciferZh/SMPL/blob/master/README.md?plain=1#L6

**Comment by zhangsanfeng86** [comment]
Thanks for ur quick and useful reply!!
