### ISSUE TITLE
Regarding The parametrs in smpl pkl file

### ISSUE THREAD

**Issue by vamsi131550** [CalciferZh/SMPL#7]
what does 'J_regressor_prior '    ,    'pose'     ,    'f'     ,     'J_regressor'     ,    'betas'    ,     'kintree_table'     ,     'J', 'weights_prior'      ,       'trans'      ,       'weights'     ,      'vert_sym_idxs'     ,     'posedirs'    ,     'pose_training_info', 'bs_style'    ,        'v_template'      ,          'shapedirs'    ,     'bs_type'   in smpl pkl file means ..What values they define .. what is the use of them each..? Thanks in Advance.

**Comment by CalciferZh** [comment]
Please refer to my comments in the code and the original paper.
