### ISSUE TITLE
What's the meaning of "quad structure"?

### ISSUE THREAD

**Issue by nnop** [CalciferZh/SMPL#71]
Thanks for providing such a pedagogical repo for SMPL.
The SMPL paper says,
> ..., it has a low-polygon count, a simple vertex topology, clean **quad structure**, a standard rig, ...

What's the meaning of **quad structure**? It didn't elaborate this term more in the paper.

**Comment by Gnimuc** [comment]
Artists prefer to use quads to model 3D shapes over triangles. You could load a .obj model with quad faces in blender and export the model to GLTF format(only support triangle faces) and load it again to see the differences.

**Comment by nnop** [comment]
Thanks, now I get it.
